### ISSUE TITLE
Create Unit Testing

### ISSUE THREAD

**Issue by JahmalEnnis** [BranniganLab/nougat#134]
- [x] convertRadianToDegree
- [x] fitVecsToSel
- [x] calculateLsqNormFactor
- [x] fitTailVectors
- [x] concatenateList
- [x] findHeadsAndTails
- [x] rotateSystem
- [x] assignLeaflet
- [x] printBinInfo
- [x] printValue
- [x] printFrame
- [x] analyzeTails
- [x] numberTails
- [x] assignBins
- [x] createOutfiles
- [x] measureBoxSize
- [x] prepareBins
- [x] calculateReferenceHeight
- [x] getSelInfo
- [x] updateDimensions
- [x] concatenateNames
- [x] createResidueDictionaries
- [x] outputDensityNormInfo
- [x] sortTailLength
- [x] getCosineTheta
- [x] calculateOrderParameters
- [x] averageTiltAndOrderParameter
- [x] averageHeightAndDensity
- [x] calculateLsqNormFactor
- [x] setBetaValues
- [x] readPolar
- [x] createAtomSelections

**Comment by JahmalEnnis** [comment]
July 21 Sprint includes
- convertRadianToDegree
- calculateLsqNormFactor
- readPolar
- calculateOrderParameters

**Comment by JahmalEnnis** [comment]
- [ ] printBinInfo
- [ ] printValue
- [ ] printFrame
- [ ] analyzeTails
- [ ] numberTails
- [ ] assignBins
- [ ] createOutfiles

**Comment by JahmalEnnis** [comment]
-[] createAtomSelections
-[] setBetaValues
-[] averageTiltAndOrderParameter
-[] averageHeightAndDensity
-[] prepareBins
-[] updateDimensions

**Comment by JesseSandberg** [comment]
Jahmal will finish all tests by Sept 1
