### ISSUE TITLE
_traj_to_3darray() function can be replaced with numpy expand_dims function

### ISSUE THREAD

**Issue by JahmalEnnis** [BranniganLab/nougat#329]
It may be possible to replace the custom _traj_to_3darray() function with a numpy maintained function with similar behavior. 

Both of these lines of code gave the same result. However, this has not been completely tested. 

* `membrane.children['z_zero'].traj._traj_to_3darray()`
* `np.expand_dims(membrane.children['z_zero'].traj[0],axis=0)`

**Comment by JesseSandberg** [comment]
@JahmalEnnis replacing the code of _traj_to_3darray() with 

return np.expand_dims(self[0], axis=0)

does not pass acceptance testing.
