### ISSUE TITLE
pore lipids sorter needs to be improved

### ISSUE THREAD

**Issue by JesseSandberg** [BranniganLab/nougat#39]
lgDT system shows significant lipids in inner leaflet pore at much greater heights than rest of leaflet

**Comment by gbrannigan** [comment]
So this sounds like an actual bug, but the issue name is written like a task.  

For bugs, make the issue name the actual observed behavior and tag it with "Bug"

**Comment by JesseSandberg** [comment]
turns out it wasn't a bug - I just hadn't turned the pore sorter on :)
