### ISSUE TITLE
Protein_Position crashes with error

### ISSUE THREAD

**Issue by JesseSandberg** [BranniganLab/nougat#41]
Need to update (at a minimum)

**Comment by gbrannigan** [comment]
Can you provide more details please @JesseSandberg

**Comment by JesseSandberg** [comment]
At a minimum, all that needs to happen is to fix the inputs it takes - it errors the second you call it at the moment. 

Ideally, we would actually make it simpler/smarter (I never rewrote this proc - it is inherited from the previous tenant)

Ultimately, this is a low priority fix. Protein_Position is just aesthetic and has nothing to do with the analysis.

**Comment by gbrannigan** [comment]
Ok please change the issue name to something like "Protein_Position crashes with error"
