### ISSUE TITLE
revise procs that use $headnames to handle different number of heads than tails

### ISSUE THREAD

**Issue by JesseSandberg** [BranniganLab/nougat#42]
setting headnames to PO4 breaks things (only one headname)

**Comment by JesseSandberg** [comment]
The code assumes that there are as many $headnames as lipid tails, which is not accurate depending on what you want your surface to be. So let's fix that :)

**Comment by gbrannigan** [comment]
Can you please modify the issue name to be a task?

**Comment by JesseSandberg** [comment]
An earlier feature implementation made it so that this is no longer an issue

**Comment by JesseSandberg** [comment]
I verified that setting different number of headnames to tails does not alter the results in any way (except the height field is slightly different, but that is expected)
