### ISSUE TITLE
User should be able to Combine or seperate graphs by leaflet or by tail in nougat.py

### ISSUE THREAD

**Issue by JahmalEnnis** [BranniganLab/nougat#65]
Ability to graph information between leaflets and chains together on same plot

**Comment by JesseSandberg** [comment]
This is potentially a duplicate of #27

**Comment by JesseSandberg** [comment]
also @JahmalEnnis nougat already separates things by leaflet. Can you tell me a use case for combining leaflets together?

**Comment by JesseSandberg** [comment]
closing as duplicate of issue #27
