### ISSUE TITLE
local height, tilt, order, density, ect.. information around inclusion

### ISSUE THREAD

**Issue by JahmalEnnis** [BranniganLab/nougat#66]

**Comment by JesseSandberg** [comment]
Thanks Jahmal! Are you just looking for a zoomed in view of what nougat already provides (heatmap)? Or are you looking for a different type of analysis?

**Comment by JesseSandberg** [comment]
Talked to Jahmal - zoomed in view is in development already. We also discussed whether or not we could get a speed boost for nougat.tcl by doing this - that would require a different effort. I'm closing this and opening two new issues, one for each item.
